# Generated by Django 4.2.6 on 2023-10-30 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('linea', models.IntegerField(choices=[(0, 'TopLane'), (1, 'MidLane'), (2, 'Jungle'), (3, 'ADC'), (4, 'Support')], default=0)),
                ('region', models.IntegerField(choices=[(0, 'Aguas Estancadas'), (1, 'Ciudad de Bundle'), (2, 'Demacia'), (3, 'El Vacio'), (4, 'Freljord'), (5, 'Islas de la Sombra'), (6, 'Ixtal'), (7, 'Jonia'), (8, 'Noxus'), (9, 'Piltover'), (10, 'Shurima'), (11, 'Targon'), (12, 'Zaun')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Coleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('fechaSalida', models.DateField()),
                ('tematica', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('rareza', models.IntegerField(choices=[(0, 'Basica'), (1, 'Unica'), (2, 'Clasica'), (3, 'Real'), (4, 'Imperial'), (5, 'Epica'), (6, 'Legendaria'), (7, 'Definitiva'), (8, 'Hextech'), (9, 'Limitada'), (10, 'Victoriosa')], default=0)),
                ('nombre', models.TextField(max_length=50)),
                ('coleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins', to='WikiLoL.coleccion')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=40)),
                ('ratio', models.IntegerField()),
                ('tecla', models.IntegerField(choices=[(0, 'Tecla Q'), (1, 'Tecla W'), (2, 'Tecla E'), (3, 'Tecla R')], default=0)),
                ('campeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='WikiLoL.campeon')),
            ],
        ),
    ]
