# Generated by Django 4.2.6 on 2023-10-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WikiLoL', '0003_alter_habilidad_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidad',
            name='ratio',
            field=models.IntegerField(choices=[(0, 'Attack Damage'), (1, 'Ability Power'), (2, 'True damage'), (3, 'AP & AD')], default=0),
        ),
    ]
